{{ if eq .Environment "e2e" }}
{{ range $pool := split "default-worker-splitaz,default-worker,worker-limit-az,worker-instance-storage,default-worker-spotio" "," }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-reserve-{{$pool}}
  labels:
    application: pool-reserve
spec:
  replicas: 1
  selector:
    matchLabels:
      application: pool-reserve
      pool: "{{$pool}}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: pool-reserve
        pool: "{{$pool}}"
    spec:
      nodeSelector:
      {{ if eq $pool "default-worker-spotio" }}
        dedicated: spotio
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: spotio
      {{ else }}
        node.kubernetes.io/node-pool: "{{$pool}}"
      {{ end }}
      terminationGracePeriodSeconds: 0
      containers:
      - name: pause
        image: registry.opensource.zalan.do/teapot/pause-amd64:3.2
        resources:
          limits:
            cpu: 1m
            memory: 50Mi
          requests:
            cpu: 1m
            memory: 50Mi
---
{{ end }}
{{ end }}
